name: 📝 Feedback
description: Provide feedback or suggestions to help improve BAUG events and content.
title: "Feedback [replace me with a title!]"
labels: ["Feedback"]
assignees:
  - joshmer2001
body:
  - type: markdown
    attributes:
      value: |
        🙏 Thank you for taking the time to provide feedback! Please fill out the form below so we can understand your thoughts and improve.

  - type: dropdown
    id: feedback_type
    attributes:
      label: Feedback Type
      description: Please let us know if this is around a specific event, topic, or general feedback.
      options:
        - Specific Event
        - Venue/Dietary
        - Topics/Speakers
        - General/Other
    validations:
      required: true
      
  - type: input
    id: feedback_summary
    attributes:
      label: Summary of Feedback
      description: Please provide a brief summary of your feedback - if its about a specific event, speakers, or topics, please detail this here.
      placeholder: e.g., 01/01/2025 Event - Both sessions too complex and too fast-paced
    validations:
      required: true

  - type: input
    id: feedback_source
    attributes:
      label: (Optional) How did you attend or hear about BAUG or a specific event with us?
      description: This helps us understand our reach and audience.
      placeholder: e.g., Through a friend, LinkedIn, previous event
