name: 💡 Topic Suggestion
description: Suggest a topic you'd like us to cover at a future BAUG event.
title: "Topic Suggestion Request"
labels: ["Topic"]
assignees:
  - joshmer2001
body:
  - type: markdown
    attributes:
      value: |
        👋 Thanks for suggesting a topic! Please fill out the form below so we can better understand your idea.

  - type: input
    id: topic_title
    attributes:
      label: Suggested Topic Name
      description: What is the topic you are suggesting?
      placeholder: e.g., Getting Started with Azure Container Apps
    validations:
      required: true

  - type: input
    id: topic_description
    attributes:
      label: Description or Key Points
      description: Tell us more about what you want covered. This helps us plan the session better.
      placeholder: e.g., What questions should it answer? Any specific tools or demos?
    validations:
      required: true

  - type: input
    id: suggested_speaker
    attributes:
      label: (Optional) Suggest a Speaker
      description: Know someone who could speak on this topic? Add their name or org here.
      placeholder: e.g., Jane Doe from Microsoft

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
