name: 💡 Topic Suggestion
description: Suggest a topic you'd like us to cover at a future BAUG event.
title: "Topic: [e.g., Getting Started with Azure Container Apps]"
labels: ["Topic"]
assignees:
  - joshmer2001
body:
  - type: markdown
    attributes:
      value: |
        👋 Thanks for suggesting a topic! Please fill out the form below so we can better understand your idea.

  - type: input
    id: topic_description
    attributes:
      label: (Optional) Description or Key Points
      description: Tell us more about what you want covered. This helps us plan the session better.
      placeholder: e.g., What questions should it answer? Any specific tools or demos?

  - type: textarea
    id: suggested_speaker
    attributes:
      label: (Optional) Suggest a Speaker
      description: Know someone who could speak on this topic? Add their name or org here.
      placeholder: e.g., Jane Doe from Microsoft

